apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.serviceName }}
  template:
    metadata:
      labels:
        app: {{ .Values.serviceName }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      terminationGracePeriodSeconds: 5

      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      
      containers:
      - name: {{ .Values.serviceName }}
        securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        
        
        ports:
        - containerPort: {{ .Values.containerPort }}
        env:
        {{- range .Values.containerEnv}}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end}}
      
        {{- if .Values.HealthCheck }}
        livenessProbe:  
          {{- toYaml .Values.livenessProbe | nindent 10 }}
        
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 12 }}
        {{- end }}
         
        {{- if .Values.cpulimit }}
        resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- end}}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
         

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.Namespace }}
spec:
  type: {{ .Values.serviceType }}
  selector:
    app: {{ .Values.serviceName }}
  ports:
  - protocol: TCP
    port: {{ .Values.servicePort }}
    targetPort: {{ .Values.containerPort }}