apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: git@github.com:bendraabdelali/Microservice-Automated-Deployment-to-kubernetes-Cluster.git
      targetRevision: HEAD
      path: charts/redis
      helm:
        valueFiles:
          - values.yaml
          - ../values/redis.yaml

    - repoURL: git@github.com:bendraabdelali/Microservice-Automated-Deployment-to-kubernetes-Cluster.git
      targetRevision: HEAD
      path: charts/Microservices
      helm:
        valueFiles:
          - values.yaml
          - values/adservice.yaml
          - values/checkoutservice.yaml
          - values/currencyservice.yaml
          - values/emailservice.yaml
          - values/frontend.yaml
          - values/paymentservice.yaml
          - values/productcatalogservice.yaml
          - values/recommendationservice.yaml
          - values/shippingservice.yaml
          - values/cartservice

  destination:
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
