apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: git@github.com:bendraabdelali/Microservice-Automated-Deployment-to-kubernetes-Cluster.git
      targetRevision: HEAD
      path: charts/redis
      helm:
        valueFiles:
          - values.yaml
          - redis.yaml

    - repoURL: git@github.com:bendraabdelali/Microservice-Automated-Deployment-to-kubernetes-Cluster.git
      targetRevision: HEAD
      path: charts/microservices
      helm:
        valueFiles:
          - values.yaml
          - values/emailservice.yaml

    - repoURL: git@github.com:bendraabdelali/Microservice-Automated-Deployment-to-kubernetes-Cluster.git
      targetRevision: HEAD
      path: charts/microservices
      helm:
        valueFiles:
          - values.yaml
          - values/recommendationservice.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: microservices

  syncPolicy:
    retry:
      limit: 2

    automated:
      prune: true
      selfHeal: true
      allowEmpty: false

    syncOptions:
      - CreateNamespace=true
      - Replace=true
