serviceName: adservice
Namespace: microservices
replicaCount: 1
containerPort: 9555
servicePort: 9555
HealthCheck: True
containerEnv:
  - name: PORT
    value: "9555"
  - name: DISABLE_PROFILER
    value: "1"

image:
  repository: microservicesb.azurecr.io/adservice
  pullPolicy: IfNotPresent
  tag: "1.1.43"

readinessProbe:
  periodSeconds: 5
  tcpSocket:
    port: 9555
livenessProbe:
  periodSeconds: 5
  tcpSocket:
    port: 9555

resources:
  requests:
    cpu: 200m
    memory: 180Mi
  limits:
    cpu: 300m
    memory: 300Mi
