serviceName: cartservice
Namespace: microservices
replicaCount: 1
containerPort: 7070
servicePort: 7070

containerEnv:
  - name: REDIS_ADDR
    value: "redis-cart:6379"
image:
  repository: gcr.io/google-samples/microservices-demo/cartservice
  #microservicesb.azurecr.io/cartservice
  pullPolicy: IfNotPresent
  tag: "v0.2.3"
