serviceName: checkoutservice
Namespace: microservices
replicaCount: 1
containerPort: 5050
servicePort: 5050

containerEnv:
  - name: PORT
    value: "5050"
  - name: PRODUCT_CATALOG_SERVICE_ADDR
    value: "productcatalogservice:3550"
  - name: SHIPPING_SERVICE_ADDR
    value: "shippingservice:50051"
  - name: PAYMENT_SERVICE_ADDR
    value: "paymentservice:50051"
  - name: EMAIL_SERVICE_ADDR
    value: "emailservice:5000"
  - name: CURRENCY_SERVICE_ADDR
    value: "currencyservice:7000"
  - name: CART_SERVICE_ADDR
    value: "cartservice:7070"

image:
  repository: microservicesb.azurecr.io/checkoutservice
  pullPolicy: IfNotPresent
  #tag: "v0.2.3"

HealthCheck: True
# readinessProbe:
#   periodSeconds: 5
#   exec:
#   command: ["/bin/grpc_health_probe", "-addr=:5050"]
# livenessProbe:
#   periodSeconds: 5
#   exec:
#   command: ["/bin/grpc_health_probe", "-addr=:5050"]
readinessProbe:
  periodSeconds: 5
  tcpSocket:
    port: 5050
livenessProbe:
  periodSeconds: 5
  tcpSocket:
    port: 5050

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
