serviceName: currencyservice
Namespace: microservices
replicaCount: 1
containerPort: 7000
servicePort: 7000

containerEnv:
  - name: PORT
    value: "7000"
  - name: DISABLE_PROFILER
    value: "1"

image:
  repository: gcr.io/google-samples/microservices-demo/currencyservice
  #microservicesb.azurecr.io/currencyservice
  pullPolicy: IfNotPresent
  tag: "v0.6.0"

HealthCheck: True

# readinessProbe:
#   periodSeconds: 5
#   exec:
#    command: ["/bin/grpc_health_probe", "-addr=:7000"]
# livenessProbe:
#   periodSeconds: 5
#   exec:
#    command: ["/bin/grpc_health_probe", "-addr=:7000"]

readinessProbe:
  periodSeconds: 5
  tcpSocket:
    port: 7000
livenessProbe:
  periodSeconds: 5
  tcpSocket:
    port: 7000
