serviceName: currencyservice
Namespace: microservices
replicaCount: 1
containerPort: 7000
servicePort: 7000

containerEnv:
  - name: PORT
    value: "7000"
  - name: DISABLE_PROFILER
    value: "1"

image:
  repository: microservicesb.azurecr.io/currencyservice
  pullPolicy: IfNotPresent
  tag: "1.1.4"

HealthCheck: True

readinessProbe:
  periodSeconds: 5
  tcpSocket:
    port: 7000
livenessProbe:
  periodSeconds: 5
  tcpSocket:
    port: 7000
