serviceName: emailservice
Namespace: microservices
replicaCount: 1
containerPort: 8080
servicePort: 5000

containerEnv:
  - name: PORT
    value: 8080
  - name: DISABLE_PROFILER
    value: 1

image:
  repository: microservicesb.azurecr.io/emailservice
  pullPolicy: IfNotPresent
  tag: "1.1.2"

HealthCheck: True

readinessProbe:
  periodSeconds: 5
  tcpSocket:
    port: 8080
livenessProbe:
  periodSeconds: 5
  tcpSocket:
    port: 8080
