serviceName: emailservice
Namespace: microservices
replicaCount: 1
containerPort: 8080
servicePort: 5000

containerEnv:
  - name: PORT
    value: 8080
  - name: DISABLE_PROFILER
    value: 1

image:
  repository: gcr.io/google-samples/microservices-demo/emailservice
  #microservicesb.azurecr.io/emailservice
  pullPolicy: IfNotPresent
  tag: "v0.6.0"

HealthCheck: True

# readinessProbe:
#   periodSeconds: 5
#   exec:
#   command: ["/bin/grpc_health_probe", "-addr=:8080"]
# livenessProbe:
#   periodSeconds: 5
#   exec:
#   command: ["/bin/grpc_health_probe", "-addr=:8080"]
readinessProbe:
  periodSeconds: 5
  tcpSocket:
    port: 8080
livenessProbe:
  periodSeconds: 5
  tcpSocket:
    port: 8080
