serviceName: productcatalogservice
Namespace: microservices
replicaCount: 1
containerPort: 3550
servicePort: 3550

containerEnv:
  - name: PORT
    value: "3550"
  - name: DISABLE_PROFILER
    value: "1"

image:
  repository: microservicesb.azurecr.io/productcatalogservice
  pullPolicy: IfNotPresent
  tag: "1.1.1"

HealthCheck: True

# readinessProbe:
#   periodSeconds: 5
#   exec:
#   command: ["/bin/grpc_health_probe", "-addr=:3550"]
# livenessProbe:
#   periodSeconds: 5
#   exec:
#   command: ["/bin/grpc_health_probe", "-addr=:3550"]
readinessProbe:
  periodSeconds: 5
  tcpSocket:
    port: 3550
livenessProbe:
  periodSeconds: 5
  tcpSocket:
    port: 3550
