serviceName: recommendationservice
Namespace: microservices
replicaCount: 1
containerPort: 8080
servicePort: 8080

containerEnv:
  - name: PORT
    value: "8080"
  - name: PRODUCT_CATALOG_SERVICE_ADDR
    value: "productcatalogservice:3550"
  - name: DISABLE_PROFILER
    value: "1"

image:
  repository: microservicesb.azurecr.io/recommendationservice
  pullPolicy: IfNotPresent
  #tag: "v0.2.3"

HealthCheck: True

# readinessProbe:
#   periodSeconds: 5
#   exec:
#   command: ["/bin/grpc_health_probe", "-addr=:8080"]
# livenessProbe:
#   periodSeconds: 5
#   exec:
#   command: ["/bin/grpc_health_probe", "-addr=:8080"]
readinessProbe:
  periodSeconds: 5
  tcpSocket:
    port: 8080
livenessProbe:
  periodSeconds: 5
  tcpSocket:
    port: 8080
