serviceName: ""
Namespace: argocd
replicaCount: 1
HealthCheck: false
cpulimit: false

serviceAccountName: default

#containerPort:
#servicePort:

serviceType: ClusterIP
containerEnv: []

imagePullSecrets: "pullsecret"

image:
  repository: ""
  pullPolicy: IfNotPresent
  tag: "1"

podSecurityContext:
  fsGroup: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  runAsUser: 1000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  privileged: false
  readOnlyRootFilesystem: true
  runAsUser: 1000
resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

livenessProbe: {}

readinessProbe: {}
