serviceName: "redis-cart"
Namespace: microservices
replicaCount: 1

containerMountPath: "/data"
volumeName: "redis-data"
serviceAccountName: default

#containerPort:
#servicePort:

serviceType: ClusterIP
containerEnv: []

image:
  repository: ""
  pullPolicy: IfNotPresent
  tag: ""

podSecurityContext:
  fsGroup: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  runAsUser: 1000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  privileged: false
  readOnlyRootFilesystem: true
  runAsUser: 1000


serviceName: redis-cart
Namespace: microservices
replicaCount: 1
containerPort: 6379
servicePort: 6379

image:
  repository: redis
  pullPolicy: IfNotPresent
  tag: "alpine"

